import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { QueryProvider } from "./QueryProvider";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ['100', '300', '400', '700', '900'],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <QueryProvider>
        <html lang="en">
          <body className={`${lato.className} bg-white antialiased`}>
            {children}
          </body>
        </html>
      </QueryProvider>
    </StoreProvider>
  );
}
